---

- name: Ensure folder exists
  file:
    path: "{{ vitam_defaults.folder.root_path }}/script/offer"
    state: directory
    owner: "{{ vitam_defaults.users.vitam }}"
    group: "{{ vitam_defaults.users.group }}"
    mode: "{{ vitam_defaults.folder.folder_permission }}"
  notify:
    - restart service

- name: Copy simulate dd command for tape into script directory
  template:
    src: "simulate_dd.sh.j2"
    dest: "{{ vitam_defaults.folder.root_path }}/script/offer/simulate_dd.sh"
    owner: "{{ vitam_defaults.users.vitam }}"
    group: "{{ vitam_defaults.users.group }}"
    mode: "{{ vitam_defaults.folder.script_permission }}"

- name: Copy simulate mt command for tape into script directory
  template:
    src: "simulate_mt.sh.j2"
    dest: "{{ vitam_defaults.folder.root_path }}/script/offer/simulate_mt.sh"
    owner: "{{ vitam_defaults.users.vitam }}"
    group: "{{ vitam_defaults.users.group }}"
    mode: "{{ vitam_defaults.folder.script_permission }}"

- name: Copy simulate mtx command for tape into script directory
  template:
    src: "simulate_mtx.sh.j2"
    dest: "{{ vitam_defaults.folder.root_path }}/script/offer/simulate_mtx.sh"
    owner: "{{ vitam_defaults.users.vitam }}"
    group: "{{ vitam_defaults.users.group }}"
    mode: "{{ vitam_defaults.folder.script_permission }}"