---

- hosts: hosts_ihm_demo
  gather_facts: no
  any_errors_fatal: true
  roles:
    - service
  vars:
    state: "{% if 'ihm-demo' not in vitam_secondary_site_components and primary_site| lower == 'false' %}stopped{% else %}started{% endif %}"
    name: vitam-ihm-demo
    hote: "{{ ip_service }}"
    port_check: "{{ vitam.ihm_demo.port_service }}"
    timeout: "{{ vitam_defaults.services.start_timeout }}"

- hosts: hosts_ihm_recette
  any_errors_fatal: true
  gather_facts: no
  roles:
    - service
  vars:
    state: "{% if 'ihm-recette' not in vitam_secondary_site_components and primary_site| lower == 'false' %}stopped{% else %}started{% endif %}"
    name: vitam-ihm-recette
    hote: "{{ ip_service }}"
    port_check: "{{ vitam.ihm_recette.port_service }}"
    timeout: "{{ vitam_defaults.services.start_timeout }}"
