---

- hosts: hosts_elasticsearch_data
  gather_facts: no
  any_errors_fatal: true
  roles:
    - service
  vars:
    state: "{% if 'elasticsearch-data' not in vitam_secondary_site_components and primary_site| lower == 'false' %}stopped{% else %}started{% endif %}"
    name: vitam-elasticsearch-data
    hote: "{{ ip_service }}"
    port_check: "{{ elasticsearch.data.port_http }}"
    timeout: "{{ vitam_defaults.services.start_timeout }}"
