---

- hosts: hosts_mongoc_data
  gather_facts: no
  any_errors_fatal: true
  roles:
    - service
  vars:
    state: "{% if 'mongoc' not in vitam_secondary_site_components and primary_site| lower == 'false' %}stopped{% else %}started{% endif %}"
    name: vitam-mongoc
    hote: "{{ ip_service }}"
    port_check: "{{ mongodb.mongoc_port }}"
    timeout: "{{ vitam_defaults.services.start_timeout }}"
  tags:
    - data

- hosts: hosts_mongod_data
  gather_facts: no
  any_errors_fatal: true
  roles:
    - service
  vars:
    state: "{% if 'mongod' not in vitam_secondary_site_components and primary_site| lower == 'false' %}stopped{% else %}started{% endif %}"
    name: vitam-mongod
    hote: "{{ ip_service }}"
    port_check: "{{ mongodb.mongod_port }}"
    timeout: "{{ vitam_defaults.services.start_timeout }}"
  tags:
    - data

- hosts: hosts_mongos_data
  gather_facts: no
  any_errors_fatal: true
  roles:
    - service
  vars:
    state: started
    name: vitam-mongos
    hote: "{{ ip_service }}"
    port_check: "{{ mongodb.mongos_port }}"
    timeout: "{{ vitam_defaults.services.start_timeout }}"
  tags:
    - data

- hosts: hosts_mongoc_offer
  gather_facts: no
  any_errors_fatal: true
  roles:
    - service
  vars:
    state: started
    name: vitam-mongoc
    hote: "{{ ip_service }}"
    port_check: "{{ mongodb.mongoc_port }}"
    timeout: "{{ vitam_defaults.services.start_timeout }}"
  tags:
    - offer

- hosts: hosts_mongod_offer
  gather_facts: no
  any_errors_fatal: true
  roles:
    - service
  vars:
    state: started
    name: vitam-mongod
    hote: "{{ ip_service }}"
    port_check: "{{ mongodb.mongod_port }}"
    timeout: "{{ vitam_defaults.services.start_timeout }}"
  tags:
    - offer

- hosts: hosts_mongos_offer
  gather_facts: no
  any_errors_fatal: true
  roles:
    - service
  vars:
    state: started
    name: vitam-mongos
    hote: "{{ ip_service }}"
    port_check: "{{ mongodb.mongos_port }}"
    timeout: "{{ vitam_defaults.services.start_timeout }}"
  tags:
    - offer
