---

- hosts: hosts_access_external
  gather_facts: no
  any_errors_fatal: true
  roles:
    - service
  vars:
    state: "{% if 'access-external' not in vitam_secondary_site_components and primary_site| lower == 'false' %}stopped{% else %}started{% endif %}"
    name: vitam-access-external
    hote: "{{ ip_service }}"
    port_check: "{{ vitam.accessexternal.port_service }}"
    timeout: "{{ vitam_defaults.services.start_timeout }}"

- hosts: hosts_ingest_external
  gather_facts: no
  any_errors_fatal: true
  roles:
    - service
  vars:
    state: "{% if 'ingest-external' not in vitam_secondary_site_components and primary_site| lower == 'false' %}stopped{% else %}started{% endif %}"
    name: vitam-ingest-external
    hote: "{{ ip_service }}"
    port_check: "{{ vitam.ingestexternal.port_service }}"
    timeout: "{{ vitam_defaults.services.start_timeout }}"
