- name: create file tree for test
  file:
    path: "{{ vitam_defaults.folder.root_path }}/data/ihm-recette/{{ item }}"
    state: directory
    owner: "{{ vitam_defaults.users.vitam }}"
    group: "{{ vitam_defaults.users.group }}"
    mode: "{{ vitam_defaults.folder.folder_permission }}"
  with_items:
    - report/performance
    - report/system
    - test-data/performance
    - test-data/system

- import_tasks: compute_offers.yml

- name: copy file for driver in data
  template:
    src: "fr.gouv.vitam.storage.offers.workspace.driver.DriverImpl"
    dest: "{{ vitam_folder_data }}/fr.gouv.vitam.storage.offers.workspace.driver.DriverImpl"
    owner: "{{ vitam_defaults.users.vitam }}"
    group: "{{ vitam_defaults.users.group }}"
    mode: "{{ vitam_defaults.folder.conf_permission }}"
  notify:
    - restart service

