---
- name: Populate service facts
  service_facts:

- block:

  - block:

    - name: Compute the mongos server list
      set_fact: mongos_item="{{ item }}"
      when:
          - "mongo_cluster_name == hostvars[item]['mongo_cluster_name']"
      with_items:
          - "{{ groups[group_name] }}"
      register: mongos_result

    - name: make a list from the result
      set_fact:
        mongos_list: "{{ mongos_result.results | remove_skipped_servers | map(attribute='ansible_facts.mongos_item') | list }}"
      when: "inventory_hostname not in single_vm_hostnames"

    - name: manage docker {{ name }}
      run_once: true
      delegate_to: "{{ mongos_list|first }}"
      docker_container:
          name: "{{ name }}"
          state: "{{ state }}"

    when: group_name is defined and group_name != ''




  - name: manage docker {{ name }}
    docker_container:
      name: "{{ name }}"
      state: "{{ state }}"
  
  when: "'docker.service' in ansible_facts.services"
