---
# tasks file for rsyslog

- name: ensure syslog-ng package is installed
  package:
    name: syslog-ng
    state: latest
  register: result
  retries: "{{ packages_install_retries_number }}"
  until: result is succeeded
  delay: "{{ packages_install_retries_delay }}"

- name: ensure service is started on boot && restart service
  service:
    name: syslog-ng
    enabled: true
    state: started
