---
# handlers file for cerebro
- name: restart cerebro
  service:
    name: vitam-elasticsearch-cerebro
    state: restarted

- name: reload consul configuration
  service:
    name: vitam-consul
    state: reloaded