---
# inspired from https://www.elastic.co/guide/en/kibana/current/migrating-6.0-index.html
- name: ensure backend is up and running
  wait_for:
    host: "{{ elasticsearch_host }}"
    port: "{{ elasticsearch_port }}"
    timeout: "{{ vitam_defaults.services.start_timeout }}"

- name: (migrate from kibana 5) Set .kibana index to read-only
  uri:
    url: http://{{ elasticsearch_host }}:{{ elasticsearch_port }}/.kibana/_settings
    method: PUT
    body: "{  \"index.blocks.write\": true }"
    body_format: json
    timeout: "{{ composant.api_call_timeout }}"

- name: (migrate from kibana 5) Create .kibana-6 index
  uri:
    url: http://{{ elasticsearch_host }}:{{ elasticsearch_port }}/.kibana-6
    method: PUT
    body: "{\"settings\" : {\"number_of_shards\" : 1,\"index.mapper.dynamic\": false},\"mappings\" : {\"doc\": {\"properties\": {\"type\": {\"type\": \"keyword\"},\"updated_at\": {\"type\": \"date\"},\"config\": {\"properties\": {\"buildNum\": {\"type\": \"keyword\"}}},\"index-pattern\": {\"properties\": {\"fieldFormatMap\": {\"type\": \"text\"},\"fields\": {\"type\": \"text\"},\"intervalName\": {\"type\": \"keyword\"},\"notExpandable\": {\"type\": \"boolean\"},\"sourceFilters\": {\"type\": \"text\"},\"timeFieldName\": {\"type\": \"keyword\"},\"title\": {\"type\": \"text\"}}},\"visualization\": {\"properties\": {\"description\": {\"type\": \"text\"},\"kibanaSavedObjectMeta\": {\"properties\": {\"searchSourceJSON\": {\"type\": \"text\"}}},\"savedSearchId\": {\"type\": \"keyword\"},\"title\": {\"type\": \"text\"},\"uiStateJSON\": {\"type\": \"text\"},\"version\": {\"type\": \"integer\"},\"visState\": {\"type\": \"text\"}}},\"search\": {\"properties\": {\"columns\": {\"type\": \"keyword\"},\"description\": {\"type\": \"text\"},\"hits\": {\"type\": \"integer\"},\"kibanaSavedObjectMeta\": {\"properties\": {\"searchSourceJSON\": {\"type\": \"text\"}}},\"sort\": {\"type\": \"keyword\"},\"title\": {\"type\": \"text\"},\"version\": {\"type\": \"integer\"}}},\"dashboard\": {\"properties\": {\"description\": {\"type\": \"text\"},\"hits\": {\"type\": \"integer\"},\"kibanaSavedObjectMeta\": {\"properties\": {\"searchSourceJSON\": {\"type\": \"text\"}}},\"optionsJSON\": {\"type\": \"text\"},\"panelsJSON\": {\"type\": \"text\"},\"refreshInterval\": {\"properties\": {\"display\": {\"type\": \"keyword\"},\"pause\": {\"type\": \"boolean\"},\"section\": {\"type\": \"integer\"},\"value\": {\"type\": \"integer\"}}},\"timeFrom\": {\"type\": \"keyword\"},\"timeRestore\": {\"type\": \"boolean\"},\"timeTo\": {\"type\": \"keyword\"},\"title\": {\"type\": \"text\"},\"uiStateJSON\": {\"type\": \"text\"},\"version\": {\"type\": \"integer\"}}},\"url\": {\"properties\": {\"accessCount\": {\"type\": \"long\"},\"accessDate\": {\"type\": \"date\"},\"createDate\": {\"type\": \"date\"},\"url\": {\"type\": \"text\",\"fields\": {\"keyword\": {\"type\": \"keyword\",\"ignore_above\": 2048}}}}},\"server\": {\"properties\": {\"uuid\": {\"type\": \"keyword\"}}},\"timelion-sheet\": {\"properties\": {\"description\": {\"type\": \"text\"},\"hits\": {\"type\": \"integer\"},\"kibanaSavedObjectMeta\": {\"properties\": {\"searchSourceJSON\": {\"type\": \"text\"}}},\"timelion_chart_height\": {\"type\": \"integer\"},\"timelion_columns\": {\"type\": \"integer\"},\"timelion_interval\": {\"type\": \"keyword\"},\"timelion_other_interval\": {\"type\": \"keyword\"},\"timelion_rows\": {\"type\": \"integer\"},\"timelion_sheet\": {\"type\": \"text\"},\"title\": {\"type\": \"text\"},\"version\": {\"type\": \"integer\"}}},\"graph-workspace\": {\"properties\": {\"description\": {\"type\": \"text\"},\"kibanaSavedObjectMeta\": {\"properties\": {\"searchSourceJSON\": {\"type\": \"text\"}}},\"numLinks\": {\"type\": \"integer\"},\"numVertices\": {\"type\": \"integer\"},\"title\": {\"type\": \"text\"},\"version\": {\"type\": \"integer\"},\"wsState\": {\"type\": \"text\"}}}}}}}"
    body_format: json
    timeout: "{{ composant.api_call_timeout }}"

- name: (migrate from kibana 5) Reindex .kibana into .kibana-6
  uri:
    url: http://{{ elasticsearch_host }}:{{ elasticsearch_port }}/_reindex
    method: POST
    body: '{"source": {"index": ".kibana"},"dest": {"index": ".kibana-6"},"script": {"inline": "ctx._source = [ ctx._type : ctx._source ]; ctx._source.type = ctx._type; ctx._id = ctx._type + \":\" + ctx._id; ctx._type = \"doc\"; ","lang": "painless"}}'
    body_format: json
    timeout: "{{ composant.api_call_timeout }}"


- name: (migrate from kibana 5) Alias .kibana-6 to .kibana and remove legacy .kibana index
  uri:
    url: http://{{ elasticsearch_host }}:{{ elasticsearch_port }}/_aliases
    method: POST
    body: "{\"actions\" : [{ \"add\":  { \"index\": \".kibana-6\", \"alias\": \".kibana\" } },{ \"remove_index\": { \"index\": \".kibana\" } }]}"
    body_format: json
    timeout: "{{ composant.api_call_timeout }}"
